import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Vault plugin directory for dev mode hot-reload
const vaultPluginDir = process.env.OBSIDIAN_VAULT_PLUGIN_DIR || "";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();

	// In dev mode, also copy to vault plugin directory if configured
	if (vaultPluginDir) {
		const { copyFileSync } = await import("node:fs");
		const copyToVault = () => {
			try {
				copyFileSync("main.js", `${vaultPluginDir}/main.js`);
				copyFileSync("styles.css", `${vaultPluginDir}/styles.css`);
				copyFileSync("manifest.json", `${vaultPluginDir}/manifest.json`);
				console.log("Copied to vault plugin directory");
			} catch (e) {
				console.error("Failed to copy to vault:", e.message);
			}
		};
		// Watch for rebuilds
		const { watch } = await import("node:fs");
		watch("main.js", copyToVault);
	}
}
